# Python入門（前編）

Pythonを学ぶにあたり、まず公式チュートリアルから始めましょう。  
http://docs.python.jp/3/tutorial/

以下では本講義で使用する環境や内容に合わせて、公式チュートリアルの要点をまとめます。

# 1. 導入

Pythonの特徴
* インタプリタ型言語なのでコンパイルが不要
* 可変長配列や辞書などの高水準の型を持つ
* 実行文のグループ化をインデントで行う
* 変数の型は代入時に決まるので、宣言不要（動的型付け）

# 2. 環境

## インストール

機械学習関連のパッケージや、短いコードを実行しながら開発できるJupyter notebookがまとめられている Anaconda 4.4.0 Python 3.6 version を使います。  
https://www.continuum.io/downloads

## 実習環境

実習は Jupyter notebookを使います。

* 作成するnotebookやデータなどを保存するフォルダを作成します。
* そのフォルダに移動してから、「New」→「Python [conda root]」を選ぶと、
Untitled.ipynbというファイルができます。
* 上部の「Untitled」をクリックして、適切なファイル名に変更します。

Jupyter notebookはCellという単位にPythonのコードや、Markdown記法による文章を記述することができます。

### よく使うMarkdown記法

* 見出し："#" (レベルは"##", "###"などで調整)
* 改行：行末で2つ以上の空白
* 箇条書き："*" と空白を先頭に。入れ子は先頭に空白を入れて、記号を"-"に変更。
* 数式："$$" で囲む

### Jupyter notebookのショートカット

* esc を押してコマンドモード
 - Enter:セルの編集
 - m: マークダウンモード
 - y: コードモード
 - c: セルのコピー
 - v: コピーしたセルのペースト
 - dd: セルの削除
 - Space: スクロールダウン
 - Shift + Space: スクロールアップ
 - h: ショートカット一覧の表示

* セルの編集モードの時
 - Shift+Enter: セルの実行、次のセルへ移動
 - ctrl +Enter: セルの実行のみ

# 3. Pythonの簡単な紹介

## 数値演算子

* 四則演算：  +, -, *, /
* 割り算の商：//, 余り： %
* べき乗： **

## 文字列

* 単引用符 ('...') もしくは二重引用符 ("...") で囲む
* 改行を含む文字列は三連引用符 ("""...""" や '''...''') を使う

## インデックス

文字列中の文字はインデックスを用いて参照できます。負の数を指定すると、右から数えます（一番後ろの文字は -1）  

変数wordに文字列'Python'を代入し、先頭の文字、5文字目、最後の文字をそれぞれ取り出してみましょう。

In [1]:
word = 'Python'

In [2]:
word[0]

'P'

In [3]:
word[5]

'n'

In [4]:
word[-1]

'n'

範囲指定は [開始インデックス:終了インデックス] と書きます。Scilabとの違いは、終了インデックスが範囲に含まれないことです。開始インデックスの省略は0、終了インデックスの省略は文字列のサイズを意味します。  

変数wordの先頭から2文字目までを取り出してみましょう。

In [5]:
word[0:2] # 終了インデックスは含まれないことに注意

'Py'

## リスト

* リストはコンマ区切りの値 (要素) の並びを角括弧で囲んだものです。
* インデックスで要素の参照や書き換えが可能です。
* 要素の追加：append() メソッド
* 要素数を求める：len() 関数の引数にリストを指定


## 簡単なプログラム

フィボナッチ数列（ http://mathtrain.jp/fibonacci ）を出力するプログラムを書いてみます。

* 10以下のフィボナッチ数を出力してみましょう
* print関数に end=',' という引数を与えて改行しないようにして、1000以下のフィボナッチ数を出力してみましょう

In [6]:
# Fibonacci series:
# the sum of two elements defines the next
a, b = 0, 1
while b < 10:
    print(b)
    a, b = b, a+b

1
1
2
3
5
8


## （追加） ベクトル、配列

ベクトルや配列は多次元配列を意味するnumpy.ndarrayを使います。1次元配列はベクトル、2次元配列は行列、3次元以上はテンソルになります。通常ndarrayを生成するときには、np.array()メソッドを使います。

変数xに5次元ベクトルを代入し、4つめの要素、先頭から2つの要素をそれぞれ取り出してみましょう。

In [7]:
import numpy as np
x= np.array([5, 3, 2, 6, 1])
x

array([5, 3, 2, 6, 1])

In [8]:
x[3]

6

In [9]:
x[0:2]

array([5, 3])

変数Xに2行3列の行列を代入し、1行目、2列目と3列目からなる行列をそれぞれ取り出してみましょう。

In [10]:
X = np.array([[0,1,2],[3,4,5]])
X

array([[0, 1, 2],
       [3, 4, 5]])

In [11]:
X[0,:]

array([0, 1, 2])

In [12]:
X[:,1:3]

array([[1, 2],
       [4, 5]])

# 4. 制御

## if文

if文は   
<code>
if 条件式:  
      条件式の値が真のとき実行する処理
else:
      条件式の値が偽のとき実行する処理
</code>  
と書きます。else以下は不要であれば省略可能です。条件分岐を重ねるときは elifを使います。  
elifを使わなければ、分岐ごとにインデントが深くなってゆきます。

整数をキーボードから入力し、負であれば0に置き換えてその旨を表示、0であればZeroと表示、1であればSingleと表示、それ以外はMoreと表示するプログラムを書いてみましょう。

In [13]:
x = int(input("Please enter an integer: "))
if x < 0:
    x = 0
    print('Negative changed to zero')
elif x == 0:
    print('Zero')
elif x == 1:
    print('Single')
else:
    print('More')

Please enter an integer: 3
More


## for文

Pythonのfor文はシーケンス型のオブジェクトから1つずつ要素を取り出して実行する書き方が基本です。  
break文やcontinue文はC言語と同じ使い方ができます。

list型変数wordsに3つの文字列を格納し、文字列とその文字数を順に表示するプログラムを書いてみましょう。

In [14]:
words = ['cat', 'window', 'defenestrate']

for w in words:
     print(w, len(w))

cat 3
window 6
defenestrate 12


ループカウンタを使うときは、range関数を用います。for文を使って0から4までを表示してみましょう。

In [15]:
for i in range(5):
     print(i)

0
1
2
3
4


range(5, 10)は5 から 9、range(0, 10, 3)は 0, 3, 6, 9でループを回します。ただし、range関数は数列を生成するわけではないことに注意が必要です。

## 関数の定義

関数の定義は  
<code>
def 関数名(引数):
    関数本体
</code>  
と書きます。

nまでのフィボナッチ数列を表示する関数fib()を作成し、動作を確認してみましょう。

In [16]:
def fib(n):    # nまでの Fibonacci 数列
    """Print a Fibonacci series up to n."""
    a, b = 0, 1
    while a < n:
        print(a, end=' ')
        a, b = b, a+b
        print()

fib(2000)

0 
1 
1 
2 
3 
5 
8 
13 
21 
34 
55 
89 
144 
233 
377 
610 
987 
1597 


値を返す場合は、関数本体中にreturn文を書きます。  
デフォルトの引数値は以下のように指定します。  
<code>
def ask_ok(prompt, retries=4, reminder='Please try again!'):
</code>

また、呼び出し側では ask(prompt='ok', reminder='NG')のようにキーワード引数を使って関数を呼び出すことができます。

# 5. データ構造

Pythonには、リスト型・タプル・辞書型などの便利なデータ構造があります。  
タプルは丸括弧の中に複数の変数をカンマで区切って保持します。辞書型はキーと値のペアの集合です。

辞書型変数telに、名前をキーとして内線番号4桁を格納してみます。新たな情報の追加や、検索が可能なことを確かめてください。

In [17]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
tel

{'guido': 4127, 'jack': 4098, 'sape': 4139}

In [18]:
tel['jack']

4098